### ISSUE TITLE
The Values are not the same

### ISSUE THREAD

**Issue by darvinrivera** [panophan/Worldometers-COVID-19-Telegram-Alert#2]
worldometers.info Data
Country: Spain
TotalCases: 9,191 
New Cases: 	+1,203	
Total Deaths: 309	
New Deaths: +15	
Total Recovered: 530		
Active Cases: 8,352
Serious	Critical: 272
Tot Cases/1M pop: 196.6

Script Data:
**Spain** COVID-19 new reports

```
Total Cases  : 8,794	(Active Cases)
New Cases    : 297		(?)
Total Deaths : +3		(?)
New Deaths   : 517		(?)
Recovered    : 7,980	(?)
Active Cases : 188.1	(?)
-
```

**Comment by panophan** [comment]
It seems Worldometers format was changed.

I'll fix it.

**Comment by panophan** [comment]
Fixed, thanks for your report.

**Comment by darvinrivera** [comment]
Worldometers format was changed..... Again.
Can you add world statistics.
