### ISSUE TITLE
zero value data error

### ISSUE THREAD

**Issue by wlangusta** [panophan/Worldometers-COVID-19-Telegram-Alert#4]
.worldometers-corona.log file has a strange format, telegram is sending wrong data
should be 325 | +38 | 5 | 0 | 13 | 307 and it is 325 | +38 | 5 | 13 | 307 | 3 zero values are read incorrectly.

**Comment by panophan** [comment]
@wlangusta can you test it again? it seem fixed.

**Comment by wlangusta** [comment]
Works, thank you  :)
